spring.application.name=Agentico

embabel.agent.platform.models.openai.api-key=${OPENAI_API_KEY}
embabel.agent.platform.models.openai.base-url=https://api.openai.com

embabel.models.default-llm=${OPENAI_DEFAULT_LLM_MODEL}
embabel.models.llms.reviewer=${OPENAI_REVIEWER_LLM_MODEL}